# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-26 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='media',
        ),
    ]
